apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: manual

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: your_root_password  # Replace with your actual root password
        - name: MYSQL_DATABASE
          value: db  # Updated database name; replace 'db' with your desired name if different
        - name: MYSQL_USER
          value: user  # Replace with your actual MySQL username
        - name: MYSQL_PASSWORD
          value: password  # Replace with your actual MySQL user password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  ports:
    - port: 3306
  selector:
    app: mysqldb
  type: ClusterIP  
