apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: spring-boot
spec:
  type: LoadBalancer  
  ports:
  - port: 8081         
    targetPort: 8089    
    protocol: TCP
  selector:
    app: spring-boot
