apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  labels:
    app: spring-boot
spec:
  type: NodePort  
  ports:
    - port: 8081         
      targetPort: 8089    
      protocol: TCP
      nodePort: 32000    # Optional: specify a port in the 30000-32767 range
  selector:
    app: spring-boot
